<?php

/**
 * @file
 * Contains migration_group.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_help().
 */
function migration_group_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migration_group module.
    case 'help.page.migration_group':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrates Drupal 7 Organic Groups to Drupal 8 Group') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function migration_group_migration_plugins_alter(array &$migrations) {
  // Don't migrate group nodes, as our own migration handles them.
  $migrations = array_filter($migrations, function (array $migration) {
    $excluded_node_types = ['working_group'];
    return (
      empty($migration['deriver'])
      ||
      $migration['deriver'] != 'Drupal\node\Plugin\migrate\D7NodeDeriver'
      ||
      !in_array($migration['source']['node_type'], $excluded_node_types)
    );
  });
}

/**
 * Implements hook_migrate_prepare_row().
 */
function migration_group_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  if ($migration->id() == 'upgrade_d7_menu_links') {
    // Working Groups are no longer nodes, so update the link paths.
    if (preg_match('|node/(\d+)|', $row->getSourceProperty('link_path'), $matches)) {
      $nid = $matches[1];
      if ($group = \Drupal\group\Entity\Group::load($nid)) {
        $row->setSourceProperty('link_path', 'group/' . $nid);
      }
    }
  }
}
